# Generated by Django 5.1.12 on 2025-09-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_create_role_models"),
        ("users", "0010_userproducttour"),
    ]

    operations = []
