# Generated by Django 5.1.9 on 2025-09-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_merge_0002_create_role_models_0010_userproducttour"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rolepermission",
            name="unique_role_permission",
        ),
        migrations.RemoveConstraint(
            model_name="userroleassignment",
            name="unique_user_role_assignment",
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission_name", "resource")},
        ),
        migrations.AlterUniqueTogether(
            name="userroleassignment",
            unique_together={("user", "role")},
        ),
    ]
