# Generated by Django 5.1.9 on 2025-12-25 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_create_project_access_model"),
    ]

    operations = [
        # Remove unique_together constraint first
        migrations.AlterUniqueTogether(
            name="projectaccess",
            unique_together=None,
        ),
        # Remove indexes that reference fields we're about to delete
        migrations.RemoveIndex(
            model_name="projectaccess",
            name="project_acc_user_id_925d6e_idx",
        ),
        migrations.RemoveIndex(
            model_name="projectaccess",
            name="project_acc_project_4392e8_idx",
        ),
        migrations.RemoveIndex(
            model_name="projectaccess",
            name="project_acc_expires_8503c6_idx",
        ),
        # Now remove fields
        migrations.RemoveField(
            model_name="projectaccess",
            name="granted_by",
        ),
        migrations.RemoveField(
            model_name="projectaccess",
            name="project",
        ),
        migrations.RemoveField(
            model_name="projectaccess",
            name="user",
        ),
        migrations.RemoveField(
            model_name="useraccess",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="useraccess",
            name="role",
        ),
        migrations.RemoveField(
            model_name="useraccess",
            name="user",
        ),
        # Now delete models
        migrations.DeleteModel(
            name="AccessLog",
        ),
        migrations.DeleteModel(
            name="ProjectAccess",
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
        migrations.DeleteModel(
            name="UserAccess",
        ),
    ]
