# Generated by Django 5.1.9 on 2025-09-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_alter_organizationmember_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="token_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="token created at"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="token_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="token expires at"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="token_used_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="token used at"
            ),
        ),
    ]
